apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-handler-7844
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-handler-7844
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
